### ISSUE TITLE
User Story #3 | Registration : As a User I can access all functionnalities without verifying my e-mail

### ISSUE THREAD

**Issue by RemiChbrnt** [SE2-2022-G17/se2022-17-Hike-Tracker#37]
When I register, an email address is required and a confirmation mail is sent. 
However the latter's verification is not mandatory to access all of the website's functionnalities, is this normal ?

I also was wondering whether the password recuperation had been implemented or not.

Thanks !

**Comment by andreaamato-polito** [comment]
The User can't access website functionalities until she verifies her account.
Password recovery is not yet implemented and is not part of the user stories we committed to.
