### ISSUE TITLE
Demo 2 issue - hut research

### ISSUE THREAD

**Issue by Mattia9918** [SE2-2022-G17/se2022-17-Hike-Tracker#61]
As a hiker I want to firstly congratulate with you for the high level of detail with which the maps have been handled.

Only suggestion, I would like to be able to select the point within which to search for the huts (with the radius you defined) with a mouse click, instead of having to enter the coordinates manually.

Thank you!

**Comment by fede1997483** [comment]
The feature you suggest is great and has been implemented. Now the hikers can select the point with a mouse click.
Thank you
