### ISSUE TITLE
Demo 2 issue - Linking hut with hike

### ISSUE THREAD

**Issue by cihanyurtsevr** [SE2-2022-G17/se2022-17-Hike-Tracker#62]
As a local guide, I really liked your app which allows me to organize my hike understandably.  

Solely, In the hut-hike link form, I'm scrolling down too much when there are many huts. I wish I could manage it by writing hut name or in an easier way.

Thank you!

**Comment by fede1997483** [comment]
The problem was solved by showing only the huts that are close to the hike.
Thank you
